In [1]:
import numpy as np

# ---- THE DATA ----

student_names = np.array(["Aisha", "Ben", "Carla", "Dev", "Eli", "Farah"])

subject_names = np.array(["Maths", "Physics", "English"])

scores = np.array([
    [78, 65, 82],
    [55, 71, 60],
    [91, 88, 79],
    [42, 38, 55],
    [67, 74, 71],
    [83, 97, 68]
])

print(scores)

total = 0

for pos in range(len(student_names)):
    Name = student_names[pos]
    total = np.sum(scores[pos, :])
    avg = np.mean(scores[pos, :])

    print(f"Name: {Name}, Total: {total}, Avg: {avg}")

[[78 65 82]
 [55 71 60]
 [91 88 79]
 [42 38 55]
 [67 74 71]
 [83 97 68]]
Name: Aisha, Total: 225, Avg: 75.0
Name: Ben, Total: 186, Avg: 62.0
Name: Carla, Total: 258, Avg: 86.0
Name: Dev, Total: 135, Avg: 45.0
Name: Eli, Total: 212, Avg: 70.66666666666667
Name: Farah, Total: 248, Avg: 82.66666666666667
