In [1]:
import numpy as np

import time


marks = np.array([10, 20, 30, 40, 50, 60])

print(marks)

marks = marks.reshape(2, 3)

print(marks)

print("Mean : ", marks.mean())

transpose = marks.T

print(transpose)

passing = marks[(marks > 40) & (marks < 60)]

print(passing)


grid = np.array([55, 72, 88, 41, 95, 63, 77, 58, 90])

grid = grid.reshape(3, 3)

print(grid.reshape(3, 3))

print(grid[1, 1])

print("middle row : ", grid[1, :])

print("last column : ", grid[:, 2])

print("Top left :", grid[0, 0])


students = np.array(["alice", "bob", "dev"])

marks = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

marks = marks.reshape(3, 3)


# YOUR TURN 4

Marks = np.array([55, 72, 88, 41, 95, 63])

names = np.array(["Aisha", "Ben", "Carla", "Dev", "Eli", "Farah"])


# 1. Students who scored above 70
Topper = names[Marks > 70]

print(Topper)


# 2. Count marks between 50 and 80
med = np.sum((Marks > 50) & (Marks < 80))

print(med)


# 3. A for 80 and above, B otherwise
print(np.where(Marks >= 80, "A", "B"))

[10 20 30 40 50 60]
[[10 20 30]
 [40 50 60]]
Mean :  35.0
[[10 40]
 [20 50]
 [30 60]]
[50]
[[55 72 88]
 [41 95 63]
 [77 58 90]]
95
middle row :  [41 95 63]
last column :  [88 63 90]
Top left : 55
['Ben' 'Carla' 'Eli']
3
['B' 'B' 'A' 'B' 'A' 'B']
